### ISSUE TITLE
getting map issue while merging

### ISSUE THREAD

**Issue by satishbkodali** [DinoChiesa/ApigeeEdge-API-Traffic-Summarizer#13]
@DinoChiesa 

I'm encountering an error while executing the check for the prior year. Can you help me understand why this is happening?

I guess the failure is because some proxies have traffic in the next month but did not have traffic in the previous month, indicating that a new proxy has been deployed. How can I handle this scenario? 

```
/Users/Documents/git/APIGEE/ApigeeEdge-API-Traffic-Summarizer/trafficByApiSummarizer.js:1148
            const addTwoArrays = (a, b) => a.map((val, ix) => val + b[ix]);
                                             ^

TypeError: Cannot read properties of undefined (reading 'map')
    at addTwoArrays (/Users/Documents/git/APIGEE/ApigeeEdge-API-Traffic-Summarizer/trafficByApiSummarizer.js:1148:46)
    at /Users/Documents/git/APIGEE/ApigeeEdge-API-Traffic-Summarizer/trafficByApiSummarizer.js:1154:44
    at Array.forEach (<anonymous>)
    at merge (/Users/Documents/git/APIGEE/ApigeeEdge-API-Traffic-Summarizer/trafficByApiSummarizer.js:1153:41)
    at /Users/Documents/git/APIGEE/ApigeeEdge-API-Traffic-Summarizer/trafficByApiSummarizer.js:1165:58
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by DinoChiesa** [comment]
🤔 Not sure.  If your analysis is correct then you'd need to use a default empty array for "a" to avoid the problem. 
like this on line 1154:
```
   merged.data[key] = addTwoArrays(merged.data[key] || [], data[key] || []);
```

**Comment by satishbkodali** [comment]
we updated it as follows and it worked fine

```
const addTwoArrays = (a, b) => a.map((val, ix) => val + b[ix]);

const merge = (unmerged) => {
  const merged = unmerged[0];
  for (let i = 1; i < unmerged.length; i++) {
    const data = unmerged[i].data;
    Object.keys(data).forEach((key) => {
      if (!merged.data[key]) {
        // Initialize the array with zeros if key doesn't exist in merged.data
        merged.data[key] = new Array(data[key].length).fill(0);
      }
      merged.data[key] = addTwoArrays(merged.data[key], data[key]);
    });
  }
  return merged;
};
```
